# -*- coding: utf-8 -*-
"""Python_Test_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9Fs-5kOMmVLRXsOnEt1xm3UudIQXu41

File link - [https://drive.google.com/drive/folders/1273osO1P2wCbn4PMNxywoMbRy7qfS1Db?usp=sharing]

The above files has the times of each athelete. Read the files and perform following operations on it.

**Problem statement:** We have to get first 3 top scores of each athelete.
- Store the data in a dictionary.
  
  Input - `Hima Das,2000-1-9,2-34,3:21,2.34,2.45,3.01,2:01,2:01,3:10,2-22,2-01,2.01,2:16`
  
  Output - `{'Name': 'Hima Das', 'DOB': '2000-1-9', 'List_of_time': ['2.34', '3.21', '2.34', '2.45', '3.01', '2.01', '2.01', '3.10', '2.22', '2.01', '2.01', '2.16']}`
- First clean the time_string as it has different special characters(2:38, 2-55, etc) inside it. Create `def sanitize(time_string):` to replace other special characters present with `.`

  Input - `['2-34', '3:21', '2.34', '2.45', '3.01', '2:01', '2:01', '3:10', '2-22', '2-01', '2.01', '2:16']`

  Expected Output - `['2.34', '3.21', '2.34', '2.45', '3.01', '2.01', '2.01', '3.10', '2.22', '2.01', '2.01', '2.16']`

- Use Comprehension to reduce code repetitions. (Optional)

- Create `def top3(time_string):` which removes duplicates from the time_string, sorts it, then returns the top 3 fastest time values.
- Use `try - except` to handle file error.
- You still must have a code with a lot of repetitions, so create a function `get_athelete_data(filename):` which will take the filename as the parameter, will call all the above created functions to return top 3 fastest time values of each athelete.

  `def get_athelete_data(filename):`
"""

from google.colab import drive
# drive.mount('/content/drive')
f=open('hima.txt')
text = f.read()
print(text)

f=open('hima.txt')
text=f.read()


a= text.split(',')
dic = {
    "Name": a[0],
    "DOB": a[1],
    "List_of_time":  a[2:]
}
print(dic)

def sanitize(list_of_time):
  for i in range (len(list_of_time)):
    dic['List_of_time'][i] = dic['List_of_time'][i].replace(':', '.').replace('-','.')
  return dic


dic = sanitize(dic['List_of_time'])
dic

#def top3(time_string):
    # Removes duplicates
    # Sorts the time_string
    # Returns Top 3 time values

def top3(list_of_time):
  res = []
  for i in list_of_time:
    if i not in res:
        res.append(i)

  res[-1]=res[-1][:4]
  res.sort()
  return res[:3]
  #return list_of_time

top3(dic['List_of_time'])

def get_athelete_data(filename):
  f=open(filename)
  text = f.read()
  a= text.split(',')
  dic = {
    "Name": a[0],
    "DOB": a[1],
    "list_of_time":  a[2:]
  }
  for i in range (len(dic['list_of_time'])):
    dic['list_of_time'][i] = dic['list_of_time'][i].replace(':', '.').replace('-','.')
  res = []
  for i in dic['list_of_time']:
    if i not in res:
        res.append(i)

  res[-1]=res[-1][:4]
  res.sort()
  print(dic['Name'],':',res[:3])

  # Open file
  # Perform all the functions inside this function and return Athelete name with top 3 time values

get_athelete_data('hima.txt')

filenames = ['hima.txt', 'dutee.txt', 'ptusha.txt', 'sekar.txt']
for i in filenames:
  get_athelete_data(i)

"""Expected Output -

Hima Das 's fastest times are:  ['2.01', '2.16', '2.22']

Dutee Chand 's fastest times are:  ['2.11', '2.23', '2.59']

PT Usha 's fastest times are:  ['2.18', '2.21', '2.22']

Sekar Dhanalakshmi 's fastest times are:  ['2.22', '2.31', '2.38']
"""